[package]
name = "wrangler"
version = "1.8.0-rc.2"
authors = ["Ashley Williams <ashley666ashley@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "wrangle your workers, CLI for rustwasm Cloudflare workers!"
readme = "README.md"
repository = "https://github.com/cloudflare/wrangler"
categories = ["wasm", "development-tools", "command-line-utilities", "web-programming"]
build = "build.rs"

[dependencies]
atty = "0.2.11"
base64 = "0.10.1"
binary-install = "0.0.3-alpha"
chrome-devtools-rs = { version = "0.0.0-alpha.0", features = ["color"] }
chrono = "0.4.9"
clap = "2.32.0"
cloudflare = "0.6.4"
config = "0.10.1"
console = "0.9.1"
data-encoding = "2.1.2"
dirs = "1.0.5"
env_logger = "0.6.1"
exitfailure = "0.5.1"
failure = "0.1.5"
flate2 = "1.0.7"
fs2 = "0.4.3"
futures = "0.3"
futures-util = "0.3"
http = "0.2.0"
hyper = "0.13.1"
hyper-tls = "0.4.0"
ignore = "0.4.10"
indicatif = "0.13.0"
lazy_static = "1.3.0"
log = "0.4.6"
notify = "4.0.12"
number_prefix = "0.3.0"
openssl = { version = '0.10.26', optional = true }
percent-encoding = "1.0.1"
predicates = "1.0.2"
prettytable-rs = "0.8.0"
rand = "0.6.5"
regex = "1"
reqwest = { version = "0.10.1", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.39"
serde_with = "1.3.1"
sha2 = "0.8.0"
tempfile = "3.1.0"
text_io = "0.1.7"
term_size = "0.3"
tokio = { version = "0.2", default-features = false, features = ["io-std", "time"] }
tokio-tungstenite = { version = "0.10.1", features = ["tls"] }
toml = "0.5.5"
url = "2.1.0"
uuid = { version = "0.8", features = ["v4"] }
which = "2.0.1"
ws = "0.9.0"

[dev-dependencies]
assert_cmd = "0.11.1"
fs_extra = "1.1.0"

[features]
vendored-openssl = ['openssl/vendored']
