[package]
name = "wrangler"
version = "1.2.0"
authors = ["Ashley Williams <ashley666ashley@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "wrangle your workers, CLI for rustwasm Cloudflare workers!"
readme = "README.md"
repository = "https://github.com/cloudflare/wrangler"
categories = ["wasm"]
build = "build.rs"

[dependencies]
atty = "0.2.11"
binary-install = "0.0.3-alpha"
clap = "2.32.0"
cloudflare = { git = "https://github.com/cloudflare/cloudflare-rs.git" }
config = "0.9.2"
console = "0.7.5"
dirs = "1.0.5"
env_logger = "0.6.1"
failure = "0.1.5"
log = "0.4.6"
openssl = { version = '0.10.11', optional = true }
reqwest = "0.9.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.39"
toml = "0.5.0"
uuid = "0.7"
which = "2.0.1"
rand = "0.6.5"
fs2 = "0.4.3"
number_prefix = "0.3.0"
flate2 = "1.0.7"
base64 = "0.10.1"
lazy_static = "1.3.0"
text_io = "0.1.7"
exitfailure = "0.5.1"
prettytable-rs = "0.8.0"
notify = "4.0.12"
ws = "0.9.0"
url = "2.1.0"
walkdir = "2.2.9"
percent-encoding = "1.0.1"
http = "0.1.1"

[dev-dependencies]
assert_cmd = "0.11.1"
fs_extra = "1.1.0"

[features]
vendored-openssl = ['openssl/vendored']
