name: â„ï¸ Linters

on: [pull_request]

jobs:
  rustfmt:
    name: ğŸ–¨ Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ğŸ—ï¸ Install Rust
        run: |
          rustup update stable
          rustup default stable
          rustup component add rustfmt
          rustup component add clippy

      - name: ğŸ§¹ Check Formatting
        run: cargo fmt --all -- --check

      - name: ğŸ§¹ Check for idiomatic code
        run: cargo clippy --all --all-features -- -D warnings
